export type SeedBiomarker = {
  loinc_code?: string;
  name: string;
  display_name?: string;
  aliases?: string[];
  default_unit_ucum: string;
  value_type?: 'numeric' | 'text' | 'numeric_or_text';
  default_ref_low?: number;
  default_ref_high?: number;
  optimal_low?: number;
  optimal_high?: number;
  categories?: string[];
  notes?: string;
};

export const seedCategories = [
  'Lipid',
  'CBC',
  'CMP',
  'Thyroid',
  'Hormones - sex',
  'Hormones - adrenal',
  'Vitamins',
  'Minerals',
  'Inflammation',
  'Iron',
  'Glycemic',
  'Liver',
  'Kidney',
  'Cardiac',
  'Autoimmunity',
  'Metals',
  'Other',
];

export const seedBiomarkers: SeedBiomarker[] = [
  // Lipid
  {
    loinc_code: '2093-3',
    name: 'Total Cholesterol',
    aliases: ['TC', 'Chol-Total'],
    default_unit_ucum: 'mg/dL',
    default_ref_low: 100,
    default_ref_high: 199,
    optimal_high: 180,
    categories: ['Lipid'],
  },
  {
    loinc_code: '2085-9',
    name: 'HDL Cholesterol',
    aliases: ['HDL', 'HDL-C'],
    default_unit_ucum: 'mg/dL',
    default_ref_low: 40,
    optimal_low: 55,
    categories: ['Lipid'],
  },
  {
    loinc_code: '13457-7',
    name: 'LDL Cholesterol',
    aliases: ['LDL', 'LDL-C'],
    default_unit_ucum: 'mg/dL',
    default_ref_high: 99,
    optimal_high: 80,
    categories: ['Lipid'],
  },
  {
    loinc_code: '2571-8',
    name: 'Triglycerides',
    aliases: ['TG'],
    default_unit_ucum: 'mg/dL',
    default_ref_low: 0,
    default_ref_high: 149,
    optimal_high: 80,
    categories: ['Lipid'],
  },
  {
    loinc_code: '49383-5',
    name: 'ApoB',
    display_name: 'Apolipoprotein B',
    aliases: ['Apo-B', 'apoB'],
    default_unit_ucum: 'mg/dL',
    optimal_high: 80,
    categories: ['Lipid', 'Cardiac'],
  },
  {
    loinc_code: '43396-1',
    name: 'Lp(a)',
    display_name: 'Lipoprotein (a)',
    aliases: ['Lp-a', 'lpa'],
    default_unit_ucum: 'nmol/L',
    optimal_high: 75,
    categories: ['Lipid', 'Cardiac'],
  },

  // CBC
  {
    loinc_code: '6690-2',
    name: 'WBC',
    display_name: 'White Blood Cells',
    default_unit_ucum: '10*3/uL',
    default_ref_low: 4,
    default_ref_high: 11,
    categories: ['CBC'],
  },
  {
    loinc_code: '789-8',
    name: 'RBC',
    display_name: 'Red Blood Cells',
    default_unit_ucum: '10*6/uL',
    default_ref_low: 4.2,
    default_ref_high: 5.9,
    categories: ['CBC'],
  },
  {
    loinc_code: '718-7',
    name: 'Hemoglobin',
    aliases: ['Hgb', 'Hb'],
    default_unit_ucum: 'g/dL',
    default_ref_low: 13.5,
    default_ref_high: 17.5,
    categories: ['CBC', 'Iron'],
  },
  {
    loinc_code: '4544-3',
    name: 'Hematocrit',
    aliases: ['Hct'],
    default_unit_ucum: '%',
    default_ref_low: 38,
    default_ref_high: 50,
    categories: ['CBC'],
  },
  {
    loinc_code: '787-2',
    name: 'MCV',
    display_name: 'Mean Corpuscular Volume',
    default_unit_ucum: 'fL',
    default_ref_low: 80,
    default_ref_high: 100,
    categories: ['CBC'],
  },
  {
    loinc_code: '785-6',
    name: 'MCH',
    default_unit_ucum: 'pg',
    default_ref_low: 27,
    default_ref_high: 33,
    categories: ['CBC'],
  },
  {
    loinc_code: '786-4',
    name: 'MCHC',
    default_unit_ucum: 'g/dL',
    default_ref_low: 32,
    default_ref_high: 36,
    categories: ['CBC'],
  },
  {
    loinc_code: '777-3',
    name: 'Platelets',
    default_unit_ucum: '10*3/uL',
    default_ref_low: 150,
    default_ref_high: 400,
    categories: ['CBC'],
  },
  {
    loinc_code: '770-8',
    name: 'Neutrophils',
    default_unit_ucum: '%',
    default_ref_low: 40,
    default_ref_high: 70,
    categories: ['CBC'],
  },
  {
    loinc_code: '736-9',
    name: 'Lymphocytes',
    default_unit_ucum: '%',
    default_ref_low: 20,
    default_ref_high: 45,
    categories: ['CBC'],
  },
  {
    loinc_code: '5905-5',
    name: 'Monocytes',
    default_unit_ucum: '%',
    default_ref_low: 2,
    default_ref_high: 12,
    categories: ['CBC'],
  },
  {
    loinc_code: '713-8',
    name: 'Eosinophils',
    default_unit_ucum: '%',
    default_ref_low: 0,
    default_ref_high: 5,
    categories: ['CBC'],
  },
  {
    loinc_code: '706-2',
    name: 'Basophils',
    default_unit_ucum: '%',
    default_ref_low: 0,
    default_ref_high: 2,
    categories: ['CBC'],
  },

  // CMP / Glycemic / Kidney / Liver
  {
    loinc_code: '2345-7',
    name: 'Glucose',
    aliases: ['Fasting Glucose', 'FBG'],
    default_unit_ucum: 'mg/dL',
    default_ref_low: 70,
    default_ref_high: 99,
    optimal_high: 90,
    categories: ['CMP', 'Glycemic'],
  },
  {
    loinc_code: '4548-4',
    name: 'HbA1c',
    display_name: 'Hemoglobin A1c',
    default_unit_ucum: '%',
    default_ref_high: 5.6,
    optimal_high: 5.2,
    categories: ['Glycemic'],
  },
  {
    loinc_code: '14749-6',
    name: 'Fasting Insulin',
    default_unit_ucum: 'uIU/mL',
    default_ref_low: 2.6,
    default_ref_high: 24.9,
    optimal_high: 5,
    categories: ['Glycemic', 'Hormones - adrenal'],
  },
  {
    loinc_code: '2160-0',
    name: 'Creatinine',
    default_unit_ucum: 'mg/dL',
    default_ref_low: 0.6,
    default_ref_high: 1.3,
    categories: ['CMP', 'Kidney'],
  },
  {
    loinc_code: '3094-0',
    name: 'BUN',
    display_name: 'Blood Urea Nitrogen',
    default_unit_ucum: 'mg/dL',
    default_ref_low: 7,
    default_ref_high: 20,
    categories: ['CMP', 'Kidney'],
  },
  {
    loinc_code: '62238-1',
    name: 'eGFR',
    display_name: 'Estimated GFR',
    default_unit_ucum: 'mL/min/1.73m2',
    default_ref_low: 60,
    categories: ['Kidney'],
  },
  {
    loinc_code: '17861-6',
    name: 'Calcium',
    default_unit_ucum: 'mg/dL',
    default_ref_low: 8.5,
    default_ref_high: 10.5,
    categories: ['CMP', 'Minerals'],
  },
  {
    loinc_code: '2951-2',
    name: 'Sodium',
    default_unit_ucum: 'mmol/L',
    default_ref_low: 136,
    default_ref_high: 145,
    categories: ['CMP'],
  },
  {
    loinc_code: '2823-3',
    name: 'Potassium',
    default_unit_ucum: 'mmol/L',
    default_ref_low: 3.5,
    default_ref_high: 5.1,
    categories: ['CMP', 'Minerals'],
  },
  {
    loinc_code: '2075-0',
    name: 'Chloride',
    default_unit_ucum: 'mmol/L',
    default_ref_low: 98,
    default_ref_high: 107,
    categories: ['CMP'],
  },
  {
    loinc_code: '2028-9',
    name: 'CO2',
    display_name: 'Carbon Dioxide',
    default_unit_ucum: 'mmol/L',
    default_ref_low: 22,
    default_ref_high: 29,
    categories: ['CMP'],
  },
  {
    loinc_code: '1751-7',
    name: 'Albumin',
    default_unit_ucum: 'g/dL',
    default_ref_low: 3.5,
    default_ref_high: 5.0,
    categories: ['CMP', 'Liver'],
  },
  {
    loinc_code: '2885-2',
    name: 'Total Protein',
    default_unit_ucum: 'g/dL',
    default_ref_low: 6.0,
    default_ref_high: 8.3,
    categories: ['CMP', 'Liver'],
  },
  {
    loinc_code: '1975-2',
    name: 'Total Bilirubin',
    default_unit_ucum: 'mg/dL',
    default_ref_low: 0.2,
    default_ref_high: 1.2,
    categories: ['CMP', 'Liver'],
  },
  {
    loinc_code: '6768-6',
    name: 'Alkaline Phosphatase',
    aliases: ['ALP'],
    default_unit_ucum: 'U/L',
    default_ref_low: 44,
    default_ref_high: 147,
    categories: ['CMP', 'Liver'],
  },
  {
    loinc_code: '1742-6',
    name: 'ALT',
    display_name: 'Alanine Aminotransferase',
    default_unit_ucum: 'U/L',
    default_ref_low: 7,
    default_ref_high: 56,
    categories: ['Liver'],
  },
  {
    loinc_code: '1920-8',
    name: 'AST',
    display_name: 'Aspartate Aminotransferase',
    default_unit_ucum: 'U/L',
    default_ref_low: 10,
    default_ref_high: 40,
    categories: ['Liver'],
  },
  {
    loinc_code: '2324-2',
    name: 'GGT',
    display_name: 'Gamma-Glutamyl Transferase',
    default_unit_ucum: 'U/L',
    default_ref_low: 9,
    default_ref_high: 48,
    categories: ['Liver'],
  },

  // Thyroid
  {
    loinc_code: '3016-3',
    name: 'TSH',
    default_unit_ucum: 'mIU/L',
    default_ref_low: 0.4,
    default_ref_high: 4.5,
    optimal_low: 0.5,
    optimal_high: 2.5,
    categories: ['Thyroid'],
  },
  {
    loinc_code: '3024-7',
    name: 'Free T4',
    aliases: ['FT4'],
    default_unit_ucum: 'ng/dL',
    default_ref_low: 0.8,
    default_ref_high: 1.8,
    categories: ['Thyroid'],
  },
  {
    loinc_code: '3051-0',
    name: 'Free T3',
    aliases: ['FT3'],
    default_unit_ucum: 'pg/mL',
    default_ref_low: 2.3,
    default_ref_high: 4.2,
    categories: ['Thyroid'],
  },
  {
    loinc_code: '5385-0',
    name: 'Reverse T3',
    aliases: ['rT3'],
    default_unit_ucum: 'ng/dL',
    default_ref_low: 8,
    default_ref_high: 25,
    categories: ['Thyroid'],
  },
  {
    loinc_code: '8099-7',
    name: 'TPO Antibodies',
    aliases: ['TPO'],
    default_unit_ucum: 'IU/mL',
    default_ref_high: 35,
    categories: ['Thyroid', 'Autoimmunity'],
  },

  // Sex hormones
  {
    loinc_code: '2986-8',
    name: 'Testosterone Total',
    aliases: ['Total Testosterone'],
    default_unit_ucum: 'ng/dL',
    default_ref_low: 264,
    default_ref_high: 916,
    optimal_low: 600,
    categories: ['Hormones - sex'],
  },
  {
    loinc_code: '2991-8',
    name: 'Free Testosterone',
    default_unit_ucum: 'pg/mL',
    default_ref_low: 9.3,
    default_ref_high: 26.5,
    categories: ['Hormones - sex'],
  },
  {
    loinc_code: '13967-5',
    name: 'SHBG',
    display_name: 'Sex Hormone Binding Globulin',
    default_unit_ucum: 'nmol/L',
    default_ref_low: 16.5,
    default_ref_high: 55.9,
    categories: ['Hormones - sex'],
  },
  {
    loinc_code: '14288-5',
    name: 'Estradiol',
    aliases: ['E2'],
    default_unit_ucum: 'pg/mL',
    default_ref_low: 7.6,
    default_ref_high: 42.6,
    categories: ['Hormones - sex'],
  },
  {
    loinc_code: '15067-2',
    name: 'FSH',
    default_unit_ucum: 'mIU/mL',
    categories: ['Hormones - sex'],
  },
  {
    loinc_code: '10501-5',
    name: 'LH',
    default_unit_ucum: 'mIU/mL',
    categories: ['Hormones - sex'],
  },
  {
    loinc_code: '2842-3',
    name: 'Prolactin',
    default_unit_ucum: 'ng/mL',
    default_ref_low: 2.0,
    default_ref_high: 18.0,
    categories: ['Hormones - sex'],
  },
  {
    loinc_code: '2143-6',
    name: 'Cortisol AM',
    display_name: 'Cortisol (AM)',
    default_unit_ucum: 'ug/dL',
    default_ref_low: 6.2,
    default_ref_high: 19.4,
    categories: ['Hormones - adrenal'],
  },
  {
    loinc_code: '2191-5',
    name: 'DHEA-S',
    display_name: 'Dehydroepiandrosterone Sulfate',
    default_unit_ucum: 'ug/dL',
    categories: ['Hormones - adrenal'],
  },

  // Vitamins / Minerals
  {
    loinc_code: '1989-3',
    name: 'Vitamin D',
    display_name: '25-Hydroxy Vitamin D',
    aliases: ['25-OH Vit D'],
    default_unit_ucum: 'ng/mL',
    default_ref_low: 30,
    default_ref_high: 100,
    optimal_low: 40,
    optimal_high: 80,
    categories: ['Vitamins'],
  },
  {
    loinc_code: '2132-9',
    name: 'Vitamin B12',
    aliases: ['B12', 'Cobalamin'],
    default_unit_ucum: 'pg/mL',
    default_ref_low: 200,
    default_ref_high: 900,
    optimal_low: 500,
    categories: ['Vitamins'],
  },
  {
    loinc_code: '2284-8',
    name: 'Folate',
    aliases: ['Folic Acid'],
    default_unit_ucum: 'ng/mL',
    default_ref_low: 5.4,
    default_ref_high: 24,
    categories: ['Vitamins'],
  },
  {
    loinc_code: '5895-7',
    name: 'Magnesium',
    aliases: ['Mg'],
    default_unit_ucum: 'mg/dL',
    default_ref_low: 1.7,
    default_ref_high: 2.2,
    categories: ['Minerals'],
  },
  {
    loinc_code: '2823-3',
    name: 'Zinc',
    default_unit_ucum: 'ug/dL',
    default_ref_low: 60,
    default_ref_high: 130,
    categories: ['Minerals'],
  },
  {
    loinc_code: '5621-7',
    name: 'Copper',
    default_unit_ucum: 'ug/dL',
    default_ref_low: 70,
    default_ref_high: 140,
    categories: ['Minerals'],
  },
  {
    loinc_code: '14685-2',
    name: 'Selenium',
    default_unit_ucum: 'ug/L',
    default_ref_low: 70,
    default_ref_high: 150,
    categories: ['Minerals'],
  },

  // Iron panel
  {
    loinc_code: '2498-4',
    name: 'Iron',
    display_name: 'Serum Iron',
    default_unit_ucum: 'ug/dL',
    default_ref_low: 60,
    default_ref_high: 170,
    categories: ['Iron'],
  },
  {
    loinc_code: '2500-7',
    name: 'TIBC',
    display_name: 'Total Iron Binding Capacity',
    default_unit_ucum: 'ug/dL',
    default_ref_low: 240,
    default_ref_high: 450,
    categories: ['Iron'],
  },
  {
    loinc_code: '2276-4',
    name: 'Ferritin',
    default_unit_ucum: 'ng/mL',
    default_ref_low: 20,
    default_ref_high: 250,
    optimal_low: 50,
    optimal_high: 150,
    categories: ['Iron', 'Inflammation'],
  },
  {
    loinc_code: '2502-3',
    name: 'Transferrin Saturation',
    aliases: ['TSAT'],
    default_unit_ucum: '%',
    default_ref_low: 20,
    default_ref_high: 50,
    categories: ['Iron'],
  },

  // Inflammation / Cardiac
  {
    loinc_code: '30522-7',
    name: 'hs-CRP',
    display_name: 'High-Sensitivity C-Reactive Protein',
    default_unit_ucum: 'mg/L',
    default_ref_high: 3.0,
    optimal_high: 1.0,
    categories: ['Inflammation', 'Cardiac'],
  },
  {
    loinc_code: '4537-7',
    name: 'ESR',
    display_name: 'Erythrocyte Sedimentation Rate',
    default_unit_ucum: 'mm/h',
    default_ref_high: 22,
    categories: ['Inflammation'],
  },
  {
    loinc_code: '13994-0',
    name: 'Homocysteine',
    default_unit_ucum: 'umol/L',
    default_ref_low: 5,
    default_ref_high: 15,
    optimal_high: 9,
    categories: ['Cardiac'],
  },
  {
    loinc_code: '34714-6',
    name: 'Uric Acid',
    default_unit_ucum: 'mg/dL',
    default_ref_low: 3.5,
    default_ref_high: 7.2,
    optimal_high: 5.5,
    categories: ['Inflammation'],
  },
  {
    loinc_code: '49563-0',
    name: 'NT-proBNP',
    display_name: 'N-terminal pro-BNP',
    default_unit_ucum: 'pg/mL',
    default_ref_high: 125,
    categories: ['Cardiac'],
  },

  // Misc
  {
    loinc_code: '6298-4',
    name: 'Vitamin A',
    display_name: 'Retinol',
    default_unit_ucum: 'ug/dL',
    default_ref_low: 32.5,
    default_ref_high: 78,
    categories: ['Vitamins'],
  },
  {
    loinc_code: '1834-1',
    name: 'Vitamin E',
    display_name: 'Alpha-Tocopherol',
    default_unit_ucum: 'mg/L',
    default_ref_low: 5.5,
    default_ref_high: 17,
    categories: ['Vitamins'],
  },
];
