import { z } from 'zod';
import {
  biomarkerTrend,
  createCustomBiomarker,
  deleteLabPanel,
  deleteLabResult,
  getBiomarker,
  getLabPanel,
  latestBiomarkers,
  listLabPanels,
  listLabResults,
  logLabPanel,
  logLabResult,
  searchBiomarker,
  setOptimalRange,
  updateBiomarker,
} from '../../services/biomarkers.js';
import { tool } from '../tool-registry.js';

const labResultInput = z.object({
  biomarker: z.string().min(1),
  value_numeric: z.number().optional(),
  value_text: z.string().optional(),
  unit_ucum: z.string().optional(),
  ref_low: z.number().optional(),
  ref_high: z.number().optional(),
  ref_text: z.string().optional(),
  interpretation: z.string().optional(),
  notes: z.string().optional(),
});

export const biomarkerTools = [
  tool({
    name: 'search_biomarker',
    description: 'Search the biomarker catalog by name, alias, or LOINC code. Filter by category.',
    group: 'biomarker',
    inputSchema: z.object({
      query: z.string().min(1),
      category: z.string().optional(),
      limit: z.number().int().positive().max(200).optional(),
    }),
    handler: (args, ctx) => searchBiomarker(ctx, args),
  }),
  tool({
    name: 'get_biomarker',
    description: 'Fetch a biomarker by id, name, or LOINC.',
    group: 'biomarker',
    inputSchema: z.object({ id_or_name: z.string().min(1) }),
    handler: (args, ctx) => getBiomarker(ctx, args.id_or_name),
  }),
  tool({
    name: 'create_custom_biomarker',
    description: 'Create a custom biomarker entry not in the seeded catalog.',
    group: 'biomarker',
    inputSchema: z.object({
      name: z.string().min(1),
      default_unit_ucum: z.string().min(1),
      value_type: z.enum(['numeric', 'text', 'numeric_or_text']).optional(),
      loinc_code: z.string().optional(),
      display_name: z.string().optional(),
      aliases: z.array(z.string()).optional(),
      categories: z.array(z.string()).optional(),
      default_ref_low: z.number().optional(),
      default_ref_high: z.number().optional(),
      optimal_low: z.number().optional(),
      optimal_high: z.number().optional(),
      notes: z.string().optional(),
    }),
    handler: (args, ctx) => createCustomBiomarker(ctx, args),
  }),
  tool({
    name: 'update_biomarker',
    description: 'Update biomarker catalog metadata (name, ranges, etc.).',
    group: 'biomarker',
    inputSchema: z.object({
      id: z.string().min(1),
      loinc_code: z.string().optional(),
      display_name: z.string().optional(),
      aliases: z.string().optional(),
      default_unit_ucum: z.string().optional(),
      value_type: z.enum(['numeric', 'text', 'numeric_or_text']).optional(),
      default_ref_low: z.number().nullable().optional(),
      default_ref_high: z.number().nullable().optional(),
      optimal_low: z.number().nullable().optional(),
      optimal_high: z.number().nullable().optional(),
      notes: z.string().nullable().optional(),
    }),
    handler: (args, ctx) => updateBiomarker(ctx, args),
  }),
  tool({
    name: 'set_optimal_range',
    description: 'Set/clear the optimal range for a biomarker (distinct from lab reference range).',
    group: 'biomarker',
    inputSchema: z.object({
      biomarker: z.string().min(1),
      low: z.number().nullable().optional(),
      high: z.number().nullable().optional(),
    }),
    handler: (args, ctx) => setOptimalRange(ctx, args),
  }),
  tool({
    name: 'log_lab_panel',
    description: 'Atomically log a lab panel (one draw, multiple results).',
    group: 'lab',
    inputSchema: z.object({
      lab_name: z.string().optional(),
      drawn_at: z.string(),
      fasting: z.boolean().optional(),
      ordered_by: z.string().optional(),
      notes: z.string().optional(),
      source: z.enum(['manual', 'pdf_import', 'api']).optional(),
      source_ref: z.string().optional(),
      panel_name: z.string().optional(),
      results: z.array(labResultInput).min(1),
    }),
    handler: (args, ctx) => logLabPanel(ctx, args),
  }),
  tool({
    name: 'log_lab_result',
    description: 'Log a single lab result without a panel.',
    group: 'lab',
    inputSchema: labResultInput.extend({ taken_at: z.string() }),
    handler: (args, ctx) => logLabResult(ctx, args),
  }),
  tool({
    name: 'list_lab_results',
    description:
      'List lab results, optionally filtered by biomarker, category, time range, or out-of-range only.',
    group: 'lab',
    inputSchema: z.object({
      biomarker: z.string().optional(),
      category: z.string().optional(),
      start: z.string().optional(),
      end: z.string().optional(),
      out_of_range_only: z.boolean().optional(),
      limit: z.number().int().positive().max(500).optional(),
    }),
    handler: (args, ctx) => listLabResults(ctx, args),
  }),
  tool({
    name: 'latest_biomarkers',
    description:
      'Most-recent value per biomarker with status (optimal/in_ref/out_of_ref) and delta vs previous.',
    group: 'biomarker',
    inputSchema: z.object({
      category: z.string().optional(),
      out_of_range_only: z.boolean().optional(),
    }),
    handler: (args, ctx) => latestBiomarkers(ctx, args),
  }),
  tool({
    name: 'biomarker_trend',
    description: 'Timeseries of values for one biomarker with per-point status.',
    group: 'biomarker',
    inputSchema: z.object({
      biomarker: z.string().min(1),
      start: z.string().optional(),
      end: z.string().optional(),
    }),
    handler: (args, ctx) => biomarkerTrend(ctx, args),
  }),
  tool({
    name: 'list_lab_panels',
    description: 'List lab panels by date range.',
    group: 'lab',
    inputSchema: z.object({
      start: z.string().optional(),
      end: z.string().optional(),
      limit: z.number().int().positive().max(200).optional(),
    }),
    handler: (args, ctx) => listLabPanels(ctx, args),
  }),
  tool({
    name: 'get_lab_panel',
    description: 'Fetch a lab panel with all its results.',
    group: 'lab',
    inputSchema: z.object({ id: z.string().min(1) }),
    handler: (args, ctx) => getLabPanel(ctx, args.id),
  }),
  tool({
    name: 'delete_lab_result',
    description: 'Delete a lab result.',
    group: 'lab',
    inputSchema: z.object({ id: z.string().min(1) }),
    handler: (args, ctx) => deleteLabResult(ctx, args.id),
  }),
  tool({
    name: 'delete_lab_panel',
    description: 'Delete a lab panel (cascades to its results).',
    group: 'lab',
    inputSchema: z.object({ id: z.string().min(1) }),
    handler: (args, ctx) => deleteLabPanel(ctx, args.id),
  }),
];
